# Generated by Django 5.1.1 on 2024-10-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='piercings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=255)),
                ('description', models.CharField(default='No description', max_length=255)),
                ('price', models.IntegerField(default=1)),
                ('photo', models.URLField(default='No_Photo')),
            ],
        ),
    ]
