# Generated by Django 5.1.1 on 2024-10-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piercings', '0002_alter_piercings_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piercings',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
