# Generated by Django 5.1.1 on 2024-12-24 04:46

import datetime
import tattoos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tattoos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No definido', max_length=255)),
                ('description', models.CharField(default='No hay descripcion', max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to=tattoos.models.file_location)),
                ('date', models.DateField(default=datetime.datetime(2024, 12, 23, 23, 46, 8, 858988))),
                ('price', models.IntegerField(default=1)),
            ],
        ),
    ]
