# Generated by Django 5.1.1 on 2024-09-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tattoos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No definido', max_length=255)),
                ('photo', models.TextField(default='No Photo availed')),
                ('price', models.IntegerField(default=5)),
            ],
        ),
    ]
