# Generated by Django 5.1.1 on 2024-12-24 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoos',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 23, 23, 46, 48, 270145)),
        ),
    ]
