# Generated by Django 5.1.1 on 2024-10-10 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoos',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 10, 9, 20, 3, 44, 876879)),
        ),
        migrations.AddField(
            model_name='tattoos',
            name='description',
            field=models.CharField(default='No hay descripcion', max_length=255),
        ),
        migrations.AlterField(
            model_name='tattoos',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
