# Generated by Django 5.1.1 on 2024-10-16 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0003_alter_tattoos_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoos',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 10, 16, 7, 10, 41, 668477)),
        ),
    ]
