# Generated by Django 5.1.1 on 2024-10-25 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0004_alter_tattoos_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoos',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 10, 25, 0, 41, 34, 250181)),
        ),
    ]
