# Generated by Django 5.1.1 on 2024-10-26 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0006_alter_tattoos_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoos',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 10, 26, 0, 52, 18, 656466)),
        ),
        migrations.AlterField(
            model_name='tattoos',
            name='photo',
            field=models.BinaryField(),
        ),
    ]
