# Generated by Django 5.1.1 on 2024-10-27 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoos', '0009_alter_tattoos_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoos',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 10, 27, 0, 2, 2, 123831)),
        ),
    ]
